### ISSUE TITLE
USER STORY: Submit a Poll Response2

### ISSUE THREAD

**Issue by amal-yusuf** [amal-yusuf/My-First-Agile-Project#4]
As a **user** I can **choose to hide my identity in the poll response** so that **to provide anonymous feedback**

## Acceptance Criteria:
* The option should be provided as a checkbox
* The checkbox should be "checked" by default
* The option should be appear next to the submit button 
* After submitting the default submission confirmation should be adjusted to include username
 
## Tasks:
- [x] Update the view: the poll design (HTML and CSS) to include the checkbox and to show the name of the submitter
- [ ] Create a new field in the model to track the username
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test functionality
