### ISSUE TITLE
USER STORY: Publish a Poll2

### ISSUE THREAD

**Issue by amal-yusuf** [amal-yusuf/My-First-Agile-Project#7]
In order **to automatically hide the poll** as an **administrator**, I can **pick the expiry date while publishing the poll**

## Acceptance Criteria:
a. The poll should disappear at 11:59 PM on the target date 
b. The real state of the "Poll" should be reserved on the home page. a message that says "Stay Tuned, a new poll is coming soon" should appear if no other Poll is active.
c. The administrator expiry date should be at least 3 days after the current date.

## Tasks:
- [x] Update the admin module view: the poll design (HTML and CSS) to include date picker
- [ ] Update the website view: Show "Stay Tuned, a new poll is coming soon"
- [ ] Create a JavaScript function to validate the expiry date is at least after 3 days 
- [ ] Create a job to check the expired Polls everyday at 11:59 PM and Hide them
- [ ] Update the controller function 
- [ ] Update unit test scripts 
- [ ] Test the functionality
